# Build stage
FROM node:20-alpine AS build
WORKDIR /app

# Copy only package files first (better caching)
COPY frontend/package*.json ./

# Install deps
RUN npm install

# Copy the actual app
COPY frontend .

# Build
RUN npm run build --verbose

# Production stage
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]